version: '3'

services:
  ctrl-money-app:
    ports:
      - "8002:80" 
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - PORT=8002
       - YFinanceHost__Url=${YFinanceHost_URL}
       - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${DATABASE_DEFAULT_PASSWORD};Server=ctrlmoney-db;Port=5432;Database=ctrlmoney-db-${ENVIRONMENT};Integrated Security=true;Pooling=true;
    networks:
      - ctrlmoney-network
  ctrlmoney-db:
    ports:
      - "15432:5432"  
    networks:
      - ctrlmoney-network
networks:
  ctrlmoney-network:
    name: ctrlmoney-network