version: '3'

services:
  ctrl-money-app:
    image: ctrl-money:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:8000"      
    environment:
       - DOTNET_ENVIRONMENT=Development
       - PORT=8000
    networks:
      - ctrl-money-stg-net
networks:
  ctrl-money-stg-net:
    external: true