version: '3'

services:
  ctrl-money-app:
    image: ctrl-money:latest
    container_name: "ctrlmoney-app-${ENVIRONMENT}"    
    build:
      context: ../
      dockerfile: Dockerfile
    links:
      - ctrlmoney-db
    depends_on:
      ctrlmoney-db:
        condition: service_healthy
  ctrlmoney-db:
    image: postgres:latest
    container_name: "ctrlmoney-db-${ENVIRONMENT}"    
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_DB: "ctrlmoney-db-${ENVIRONMENT}"    
      POSTGRES_PASSWORD: "${DATABASE_DEFAULT_PASSWORD}"      
    healthcheck:
      test: "pg_isready -q -U postgres"
networks:
  ctrlmoney-network:
    driver: bridge