version: '3.4'

services:
  ctrl-money-app:
    ports:
      - "8002:80" 
    environment:
       - DOTNET_ENVIRONMENT=Development
       - PORT=8002
       - ConnectionStrings__DefaultConnection=User ID =postgres;Password=${DATABASE_DEFAULT_PASSWORD};Server=ctrlmoney-db;Port=5432;Database=ctrlmoney-db-${ENVIRONMENT};Integrated Security=true;Pooling=true;
    networks:
      - ctrlmoney-network
  ctrlmoney-db:
    networks:
      - ctrlmoney-network
networks:
  ctrlmoney-network:
    name: ctrlmoney-network
